@startuml
'https://plantuml.com/class-diagram

class Game {
}

abstract Card{

}

class CountryCard{
- cardCountry : Country
- image : String
}

class ObjectiveCard {
}

Game --> Card
Card <|-- CountryCard
Card <|-- ObjectiveCard

@enduml